name: CD

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  cd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
      - run: yarn && yarn build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
